src/Acme.BookLibrary.Web/Pages/Authors/CreateModal.cshtml.cs
using Acme.BookLibrary.Authors;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System;
using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Form;

namespace Acme.BookLibrary.Web.Pages.Authors;

public class CreateModalModel : BookLibraryPageModel
{
    [BindProperty]
    public CreateAuthorViewModel Author { get; set; }

    private readonly IAuthorAppService _authorAppService;

    public CreateModalModel(IAuthorAppService authorAppService)
    {
        _authorAppService = authorAppService;
    }

    public void OnGet()
    {
        Author = new CreateAuthorViewModel();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        var dto = ObjectMapper.Map<CreateAuthorViewModel, CreateUpdateAuthorDto>(Author);
        await _authorAppService.CreateAsync(dto);
        return NoContent();
    }

    public class CreateAuthorViewModel
    {
        [Required]
        [StringLength(150)]
        public string Name { get; set; }

        [Required]
        [TextArea]
        public string ShortBio { get; set; }
    }
}

src/Acme.BookLibrary.Web/Pages/Books/CreateModal.cshtml.cs
using Acme.BookLibrary.Books;
using Acme.BookLibrary.Booksp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Form;

namespace Acme.BookLibrary.Web.Pages.Books;

public class CreateModalModel : BookLibraryPageModel
{
    [BindProperty]
    public CreateBookViewModel Book { get; set; }

    public List<SelectListItem> Authors { get; set; }

    private readonly IBookAppService _bookAppService;

    public CreateModalModel(IBookAppService bookAppService)
    {
        _bookAppService = bookAppService;
    }

    public async Task OnGetAsync()
    {
        Book = new CreateBookViewModel();

        var authorLookup = await _bookAppService.GetAuthorLookupAsync();
        Authors = authorLookup.Items
            .Select(x => new SelectListItem(x.Name, x.Id.ToString()))
            .ToList();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        await _bookAppService.CreateAsync(ObjectMapper.Map<CreateBookViewModel, CreateUpdateBookDto>(Book));
        return NoContent();
    }

    public class CreateBookViewModel
    {
        [HiddenInput]
        public Guid Id { get; set; }

        [Required]
        [StringLength(150)]
        public string Name { get; set; }

        [SelectItems(nameof(Authors))]
        [DisplayName("Author")]
        public Guid AuthorId { get; set; }

        [Required]
        public BookType BookType { get; set; } = BookType.Undefined;

        [Required]
        [DataType(DataType.Date)]
        public DateTime PublishDate { get; set; } = DateTime.Now;

        [HiddenInput]
        public int MaxReturnTime { get; set; } = 3;

        [Required]
        public int Quantity { get; set; }

        [Required]
        public long Price { get; set; }
    }
}

src/Acme.BookLibrary.Web/Pages/CheckoutDetails/CreateModal.cshtml.cs
using Acme.BookLibrary.Books;
using Acme.BookLibrary.CheckoutDetails;
using Acme.BookLibrary.MemberCards;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.JSInterop;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Acme.BookLibrary.Web.Pages.CheckoutDetails;

public class CreateModalModel : BookLibraryPageModel
{
    private readonly IJSRuntime _jsRuntime;
    private readonly MemberCardAppService _memberCardAppService;

    public List<BookModalView> bookModalViews { get; set; }

    [BindProperty]
    public SearchProductInput Input { get; set; } = new SearchProductInput();

    [BindProperty]
    public CreateModalModelView MemberCard { get; set; }

    private readonly BookAppService _bookAppService;

    public CreateModalModel(BookAppService bookAppService, MemberCardAppService memberCardAppService, IJSRuntime jsRuntime)
    {
        _memberCardAppService = memberCardAppService;
        _jsRuntime = jsRuntime;
        _bookAppService = bookAppService;
    }

    [BindProperty]
    public CreateUpdateCheckoutDetailDto CheckoutDetail { get; set; }

    [BindProperty]
    public BookFind bookFind { get; set; } = new BookFind();

    public class BookFind
    {
        [Required]
        public string Id { get; set; }
    }

    public void OnGet()
    {
        CheckoutDetail = new CreateUpdateCheckoutDetailDto();
        bookModalViews = new List<BookModalView>();
    }

    public async void OnPostGetInfoAsync()
    {
        var memberCard = await _memberCardAppService.GetAsync(Guid.Parse(Input.Keyword));
        MemberCard.Id = memberCard.Id.ToString();
        MemberCard.Name = memberCard.Name;
        MemberCard.Address = memberCard.Address;
        MemberCard.Phone = memberCard.Phone;
        MemberCard.Email = memberCard.Email;
    }

    public async void OnPostAddRowAsync()
    {
        Guid guid;
        bool isGuidValid = Guid.TryParse(bookFind.Id, out guid);

        if (isGuidValid)
        {
            var book = await _bookAppService.GetAsync(Guid.Parse(bookFind.Id));
            if (book == null)
            {
                return;
            }
            else
            {
                bookModalViews = bookModalViews ?? new List<BookModalView>();

                var bookModalView = new BookModalView
                {
                    Id = bookFind.Id,
                    Name = book.Name,
                    IsReturned = "false",
                    ReturnDate = DateTime.Now.AddDays(14)
                };
                bookModalViews.Add(bookModalView);
            }
        }
        else
        {
            return;
        }
        
    }

    public class CreateModalModelView
    {
        [Required]
        public DateTime ExpDate { get; set; }

        [Required]
        [StringLength(150)]
        public string Name { get; set; }

        [Required]
        public string Address { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string Phone { get; set; }

        [Required]
        public string Id { get; set; }
    }

    public class BookModalView
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string IsReturned { get; set; }
        public DateTime ReturnDate { get; set; }
    }

    public class SearchProductInput
    {
        public string Keyword { get; set; }
    }
}

src/Acme.BookLibrary.Web/Pages/CheckoutDetails/Index.cshtml.cs
using Acme.BookLibrary.MemberCards;
using Acme.BookLibrary.Members;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using static Acme.BookLibrary.Web.Pages.CheckoutDetails.CreateModalModel;

namespace Acme.BookLibrary.Web.Pages.CheckoutDetails;

public class IndexModel : PageModel
{

    public void OnGet()
    {
    }
}

src/Acme.BookLibrary.Web/Pages/MemberCards/CreateModal.cshtml.cs
using Acme.BookLibrary.MemberCards;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Acme.BookLibrary.Web.Pages.MemberCards;

public class CreateModalModel : BookLibraryPageModel
{
    [BindProperty]
    public CreateUpdateMemberCardDto Card { get; set; }

    private readonly IMemberCardAppService _memberCardAppService;

    public CreateModalModel(IMemberCardAppService memberCardAppService)
    {
        _memberCardAppService = memberCardAppService;
    }

    public void OnGet()
    {
        Card = new CreateUpdateMemberCardDto();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        await _memberCardAppService.CreateAsync(
          Card
           );
        return NoContent();
    }
}

src/Acme.BookLibrary.Web/Pages/CheckoutDetails/CreateModal.cshtml
@page
@using Acme.BookLibrary.Localization
@using Acme.BookLibrary.Web.Pages.CheckoutDetails
@using Microsoft.Extensions.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Modal
@model CreateModalModel
@inject IStringLocalizer<BookLibraryResource> L
@{
    Layout = null;
}
<abp-dynamic-form abp-model="bookFind" asp-page="/CheckoutDetails/CreateModal">
    <abp-modal>
        <abp-modal-header title="@L["Add Book"].Value"></abp-modal-header>
        <form method="post">
            <abp-modal-body>
                <abp-form-content />
            </abp-modal-body>
            <abp-modal-footer>
                <button type="submit" class="btn btn-primary" name="Addrow">Add</button>
            </abp-modal-footer>
        </form>
    </abp-modal>
</abp-dynamic-form>

src/Acme.BookLibrary.Web/Pages/CheckoutDetails/Index.cshtml
@page
@using Acme.BookLibrary.Localization
@using Acme.BookLibrary.Web.Pages.CheckoutDetails
@using Microsoft.Extensions.Localization;
@model CreateModalModel
@inject IStringLocalizer<BookLibraryResource> L
@section scripts
{
    <abp-script src="/Pages/CheckoutDetails/Index.js" />
}

<abp-card>
    <abp-card-header>
        <abp-row>
            <abp-column size-md="_3">
                <abp-card-title>@L["Information"]</abp-card-title>
            </abp-column>
            
                <abp-column size-md="_6" class="text-end">

                    <form method="post">
                    <div class="input-group">
                        <input asp-for="@Model.Input.Keyword" type="search" class="form-control shadow-none" placeholder="Id Member Card ..." aria-label="Recipient's username" aria-describedby="basic-addon2">
                        <button type="submit" name="getInfo" class="btn btn-primary" asp-page-handler="GetInfo">Search</button>
                    </div>
                    </form>

                </abp-column>
           
        </abp-row>
    </abp-card-header>
    <abp-card-body>
        <abp-row>
            <abp-column>
                <abp-input class="shadow-none" asp-for="@Model.MemberCard" value="@DateTime.Now" label="Creation Time" readonly="true" placeholder="name@example.com" />
            </abp-column>
            <abp-column>
                <abp-input class="shadow-none" asp-for="@Model.MemberCard.Id" label="Card Id" readonly="true" placeholder="Card Id ... " />
            </abp-column>
            <abp-column>
                <abp-input class="shadow-none" asp-for="@Model.MemberCard.Name" label="Name" readonly="true" placeholder="Member name ... " />
            </abp-column>
            <abp-column>
                <abp-input class="shadow-none" asp-for="@Model.MemberCard.ExpDate" label="Exp Date" readonly="true" placeholder="Exp Date ... " />
            </abp-column>
        </abp-row>
        <abp-row>
            <abp-column>
                <abp-input class="shadow-none" asp-for="@Model.MemberCard.Phone" label="Phone" readonly="true" placeholder="Phone number" />
            </abp-column>
            <abp-column>
                <abp-input class="shadow-none" asp-for="@Model.MemberCard.Email" label="Email" readonly="true" placeholder="Ex@gmail.com " />
            </abp-column>
            <abp-column>
                <abp-input class="shadow-none" asp-for="@Model.MemberCard.Address" label="Address" readonly="true" placeholder="Address ... " />
            </abp-column>
        </abp-row>
        
        
    </abp-card-body>
</abp-card>
<abp-card>
    <abp-card-header>
        <abp-row>
            <abp-column size-md="_6">
                <abp-card-title>@L["Books"]</abp-card-title>
            </abp-column>
            <abp-column size-md="_6" class="text-end">
                <form method="post">
                    <div class="input-group">
                        <input asp-for="@Model.bookFind.Id" type="search" class="form-control shadow-none" placeholder="Id Book ..." aria-label="Recipient's username" aria-describedby="basic-addon2">
                        <button type="submit" name="AddRow" class="btn btn-primary" asp-page-handler="AddRow">Add</button>
                    </div>
                </form>
            </abp-column>
        </abp-row>
    </abp-card-header>
    <abp-card-body>
        <abp-table small="true" striped-rows="true" border-style="Bordered">
            <thead Theme="Dark">
                <tr>
                    <th scope="Column">Action</th>
                    <th scope="Column">Id</th>
                    <th scope="Column">Name</th>
                    <th scope="Column">IsReturned</th>
                    <th scope="Column">Return Date</th>
                </tr>
            </thead>
            <tbody>
                @{
                    if (Model.bookModalViews == null)
                    {
                        <tr>Data is Emty</tr>
                    }
                    else
                    {
                        foreach (var i in Model.bookModalViews)
                        {
                            <tr>
                                <td>Delete</td>
                                <th>@i.Id</th>
                                <td>@i.Name</td>
                                <td>@i.IsReturned</td>
                                <td>@i.ReturnDate</td>
                            </tr>
                        }
                    }   
                }
            </tbody>
        </abp-table>
    </abp-card-body>
</abp-card>